### ISSUE TITLE
[BUG] Failed to start the Kernel.  OSError: libedit.so.2: cannot open shared object file: No such file or directory.  View Jupyter log for further details.

### ISSUE THREAD

**Issue by jamcas14** [modular/modular#3696]
### Bug description

I'm getting the following error:
Failed to start the Kernel. 
OSError: libedit.so.2: cannot open shared object file: No such file or directory. 
View Jupyter [log](command:jupyter.viewOutput) for further details.

This occurs when trying to execute mojo code in a .ipynb file inside of vscode. These are the terminal commands I have executed before the opening of vscode:
```
usr@fedora:~/code/mojo/test$ magic init mojo --format mojoproject
✔ Created /home/usr/code/mojo/test/mojo/mojoproject.toml
✔ Added max >=24.5.0,<25
usr@fedora:~/code/mojo/test$ cd mojo
usr@fedora:~/code/mojo/test/mojo$ magic shell
 . "/tmp/pixi_env_7Qa.sh"
usr@fedora:~/code/mojo/test/mojo$  . "/tmp/pixi_env_7Qa.sh"
(mojo) usr@fedora:~/code/mojo/test/mojo$ mojo --version
mojo 24.5.0 (e8aacb95)
(mojo) usr@fedora:~/code/mojo/test/mojo$ code .
(mojo) usr@fedora:~/code/mojo/test/mojo$ magic --version
magic 0.3.1 - (based on pixi 0.29.0)
```
after this, in vscode i made a file called learn.ipynb in vscode (I have the mojo extension and jupyter notebook extensions installed) and after selecting the mojo kernel when trying to run any code, the error message appears.
![image](https://github.com/user-attachments/assets/d2f70b6c-ac37-49bc-a446-edb7804a11e0)

### Steps to reproduce

See above

### System information

```shell
- What OS did you do install Mojo on ?
-> Fedora: Linux
- Provide version information for Mojo by pasting the output of `mojo -v`
See above
- Provide Magic CLI version by pasting the output of `magic -V` or `magic --version` 
See above
- Optionally, provide more information with `magic info`.
->
      Pixi version: 0.29.0
          Platform: linux-64
  Virtual packages: __unix=0=0
                  : __linux=6.8.5=0
                  : __glibc=2.39=0
                  : __archspec=1=zen2
         Cache dir: /home/jamiecasander/.cache/rattler/cache
      Auth storage: /home/jamiecasander/.rattler/credentials.json
  Config locations: No config files found

Project
------------
              Name: mojo
           Version: 0.1.0
     Manifest file: /home/jamiecasander/code/mojo/test/mojo/mojoproject.toml
      Last updated: 19-10-2024 15:20:52

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge, https://conda.modular.com/max
  Dependency count: 1
      Dependencies: max
  Target platforms: linux-64
```

**Comment by ematejska** [comment]
@walter I know lots has changed here in the past month.  Is this still an issue?

**Comment by Mogball** [comment]
This sounds like it could be a dependency issue on Fedora. Maybe magic is missing a dep?

**Comment by walter** [comment]
> @walter I know lots has changed here in the past month. Is this still an issue?

Probably not the Walter you are after. Unsubscribing to thread.

**Comment by walter-erquinigo** [comment]
@ematejska  , notebooks rely on LLDB, which have a dependency on libedit.so.2 being available on the system. This is similar to https://github.com/modularml/mojo/issues/855
Maybe Zac can figure out how to specify that dependency in the proper way

**Comment by teleporterx** [comment]
https://github.com/modularml/mojo/issues/3629#issuecomment-2495578802 worked for me to get MOJO-REPL. I just symlinked libedit.so.2 and exported LD_LIBRARY_PATH. But this is just a temporary workaround and would need to be fixed in the future.

**Comment by walter-erquinigo** [comment]
@teleporterx , do you know where your system has libedit.so.2 by default? We might be able to just add that location to the RPATH of our lldb builds.

**Comment by teleporterx** [comment]
@walter-erquinigo, on my system, the shared libraries for `libedit` are located by default in the `/usr/lib/` directory

```bash
$ ls -la /usr/lib | grep libedit.so.
lrwxrwxrwx   1 root root        17 May 25  2024 libedit.so -> libedit.so.0.0.73
lrwxrwxrwx   1 root root        17 May 25  2024 libedit.so.0 -> libedit.so.0.0.73
-rwxr-xr-x   1 root root    219248 May 25  2024 libedit.so.0.0.73
lrwxrwxrwx   1 root root        21 Nov 24 18:59 libedit.so.2 -> /usr/lib/libedit.so.0 # This symlink fixed the mojo-repl issue & was added manually
```

Here are some essential details of my system
```bash
$ uname -a                                    
Linux archusb 6.11.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:06:09 +0000 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
I’d like to clarify that I have installed the latest version of `libedit` from my distribution’s official repositories, which provides `libedit.so.0` symlinked to `libedit.so.0.0.73`. I couldn’t find `libedit.so.2` on my system, even though I’m using the most recent package available.

It seems that `libedit.so.0` (symlinked to `libedit.so.0.0.73`) is still considered the latest stable version in the repository, even though newer updates and features have been applied under that version. While the naming convention hasn’t updated the shared library version to `libedit.so.2`, the library is up-to-date and backward-compatible.

---
Another important thing to note before the activation of the `venv` using `magic shell` is that I have to define the `LD_LIBRARY_PATH` also manually **every time** to get mojo-repl to work. Without which executing `$mojo` throws an unknown error.
```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/teleporterx/Mojo/sandbox/.magic/envs/default/lib
```

Maybe even this needs to be addressed in the form of some automation to add `/.magic/envs/default/lib` to `LD_LIBRARY_PATH`

**Comment by teleporterx** [comment]
@walter-erquinigo, I've just discovered that even the `.magic` dir which is created on `magic init <some_project> --format mojoproject`also contains `libedit.so.x` (the libedit shared libraries)

```bash
$ ls -la .magic/envs/default/lib | grep libedit.so
lrwxrwxrwx  1 teleporterx teleporterx        17 Nov 24 18:58 libedit.so -> libedit.so.0.0.63
lrwxrwxrwx  1 teleporterx teleporterx        17 Nov 24 18:58 libedit.so.0 -> libedit.so.0.0.63
-rwxrwxr-x  3 teleporterx teleporterx    257808 Aug 17  2020 libedit.so.0.0.63

$ ldd .magic/envs/default/bin/mojo-lldb
.
.
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007c6e10bf0000)
	libedit.so.2 => not found
.
.

```
and if we symlink that (make sure you are in the same dir as the source)
```zsh
╭─ ~/Mo/sandbox/.magic/envs/default/lib (.venv)
╰─ sudo ln -s libedit.so.0 libedit.so.2

╭─ ~/Mo/sandbox/.magic/envs/default/lib (.venv)
╰─ mojo
error: unknown error

╭─ ~/Mo/sandbox/.magic/envs/default/lib (.venv)
╰─ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/teleporterx/Mojo/sandbox/.magic/envs/default/lib

╭─ ~/Mo/sandbox/.magic/envs/default/lib (.venv)
╰─ mojo
warning: (x86_64) /home/teleporterx/Mojo/sandbox/.magic/envs/default/lib/libstdc++.so.6 unsupported DW_FORM value: 0x1e
Welcome to Mojo! 🔥

Expressions are delimited by a blank line.
Type `:quit` to exit the REPL and `:mojo help` for further assistance.

  1>  
```
So, if you find a way to do this, you'd no longer need to depend on the OS provided shared lib for libedit.

**Comment by walter-erquinigo** [comment]
Thank you, I think I'll relax libedit.so.2 to the simpler libedit.so and that should work.

**Comment by walter-erquinigo** [comment]
Hi! Could you share the output of `objdump -p /usr/lib/libedit.so.0`.
Besides that, I'm starting to have the suspicion that we'll need a completely new build of mojo just for Fedora. We are currently only building for Ubuntu, which uses `libedit.so.2`, and we don't have Fedora builders. Eventually we'll start building for other platforms, but now in the short term.

**Comment by teleporterx** [comment]
This is the output of `objdump -p /usr/lib/libedit.so.0`

```bash
/usr/lib/libedit.so.0:     file format elf64-x86-64

Program Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
         filesz 0x0000000000005eb8 memsz 0x0000000000005eb8 flags r--
    LOAD off    0x0000000000006000 vaddr 0x0000000000006000 paddr 0x0000000000006000 align 2**12
         filesz 0x000000000001feb5 memsz 0x000000000001feb5 flags r-x
    LOAD off    0x0000000000026000 vaddr 0x0000000000026000 paddr 0x0000000000026000 align 2**12
         filesz 0x000000000000c4f4 memsz 0x000000000000c4f4 flags r--
    LOAD off    0x00000000000330d0 vaddr 0x00000000000330d0 paddr 0x00000000000330d0 align 2**12
         filesz 0x0000000000001fe0 memsz 0x0000000000005bb0 flags rw-
 DYNAMIC off    0x0000000000034660 vaddr 0x0000000000034660 paddr 0x0000000000034660 align 2**3
         filesz 0x00000000000001f0 memsz 0x00000000000001f0 flags rw-
    NOTE off    0x00000000000002a8 vaddr 0x00000000000002a8 paddr 0x00000000000002a8 align 2**3
         filesz 0x0000000000000040 memsz 0x0000000000000040 flags r--
    NOTE off    0x00000000000002e8 vaddr 0x00000000000002e8 paddr 0x00000000000002e8 align 2**2
         filesz 0x0000000000000024 memsz 0x0000000000000024 flags r--
0x6474e553 off    0x00000000000002a8 vaddr 0x00000000000002a8 paddr 0x00000000000002a8 align 2**3
         filesz 0x0000000000000040 memsz 0x0000000000000040 flags r--
EH_FRAME off    0x000000000002dcd4 vaddr 0x000000000002dcd4 paddr 0x000000000002dcd4 align 2**2
         filesz 0x0000000000000c9c memsz 0x0000000000000c9c flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
   RELRO off    0x00000000000330d0 vaddr 0x00000000000330d0 paddr 0x00000000000330d0 align 2**0
         filesz 0x0000000000001f30 memsz 0x0000000000001f30 flags r--

Dynamic Section:
  NEEDED               libncursesw.so.6
  NEEDED               libc.so.6
  SONAME               libedit.so.0
  INIT                 0x0000000000006000
  FINI                 0x0000000000025ea8
  INIT_ARRAY           0x00000000000330d0
  INIT_ARRAYSZ         0x0000000000000008
  FINI_ARRAY           0x00000000000330d8
  FINI_ARRAYSZ         0x0000000000000008
  GNU_HASH             0x0000000000000310
  STRTAB               0x00000000000030a0
  SYMTAB               0x0000000000000eb0
  STRSZ                0x0000000000001337
  SYMENT               0x0000000000000018
  RELA                 0x0000000000004780
  RELASZ               0x00000000000016c8
  RELAENT              0x0000000000000018
  FLAGS                0x0000000000000008
  FLAGS_1              0x0000000000000001
  VERNEED              0x00000000000046b0
  VERNEEDNUM           0x0000000000000002
  VERSYM               0x00000000000043d8
  RELR                 0x0000000000005e48
  RELRSZ               0x0000000000000070
  RELRENT              0x0000000000000008

Version References:
  required from libncursesw.so.6:
    0x00574d03 0x00 04 NCURSES6_TINFO_5.0.19991023
  required from libc.so.6:
    0x00fd0e42 0x00 12 GLIBC_ABI_DT_RELR
    0x0d696913 0x00 11 GLIBC_2.3
    0x06969191 0x00 10 GLIBC_2.11
    0x069691b8 0x00 09 GLIBC_2.38
    0x06969194 0x00 08 GLIBC_2.14
    0x069691b3 0x00 07 GLIBC_2.33
    0x0d696914 0x00 06 GLIBC_2.4
    0x06969197 0x00 05 GLIBC_2.17
    0x09691974 0x00 03 GLIBC_2.3.4
    0x09691a75 0x00 02 GLIBC_2.2.5
```

**Comment by walter-erquinigo** [comment]
Oof, the soname is libedit.so.0, that means that we need to have a completely new build for fedora and similar systems.

@zbowling , do you know if that's in the works or we'll just support ubuntu for the time being?

**Comment by zbowling** [comment]
@walter-erquinigo Yeah we have seen this before. The LLDB build in mojo links the libedit/GNU readline on the ubuntu machine we build on and it's got a versioned in the so link name. I've worked around this issue by creating a symlink for libedit.so.2 as a cheap hack when on different on different distros (other versions of libedit work fine). We can get readline/libedit from conda-forge and I've also done an LD_PRELOAD hack to force mojo use that version instead of trying of use the system version. We have to change how we build mojo in CI to fix it though to make sure it picks up on readline properly.

**Comment by walter-erquinigo** [comment]
Interesting. So, can we build in CI against a non-versioned libedit.so?

**Comment by prateekshukla1108** [comment]
The problem is still not solved, Any updates??

**Comment by Ahajha** [comment]
Sorry, none yet. I had poked around with this a few weeks ago, but got it mixed up with another issue. But thanks for mentioning that it's still an issue, I'll try to revisit this soon.

**Comment by prateekshukla1108** [comment]
Yeah, I am currently on nixos and its super difficult to fix it because of its read only file system. 
Can't link it or do any modifications without damaging my whole system

**Comment by Ahajha** [comment]
This should be fixed in the next nightly!

**Comment by taylorpool** [comment]
This is still a problem for me on NixOS. Any suggestions of what to try @Ahajha @prateekshukla1108 ?


Mojo 25.6.0.dev2025090305 (7dadb996)

mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory

**Comment by prateekshukla1108** [comment]
@taylorpool Since nixos is immutable there's not a lot which you can do. Just try updating pixi or something else

**Comment by Ahajha** [comment]
We've updated the versioning for Mojo in preparation for a future 1.0, can you try installing `mojo<1.0.0`? You should get something like `0.25.6.0.dev...`. I'm working on yanking the old packages so that this headache is only temporary.

**Comment by taylorpool** [comment]
I installed `mojo<1.0.0`

`mojo --version` now gives
`Mojo 0.25.6.0.dev2025091705 (adcfffed)`

`pixi info` gives
```
System
------------
       Pixi version: 0.54.1
           Platform: linux-64
   Virtual packages: __unix=0=0
                   : __linux=6.12.43=0
                   : __glibc=2.40=0
                   : __cuda=12.8=0
                   : __archspec=1=zen4
          Cache dir: /home/tpool/.cache/rattler/cache
       Auth storage: /home/tpool/.rattler/credentials.json
   Config locations: No config files found

Global
------------
            Bin dir: /home/tpool/.pixi/bin
    Environment dir: /home/tpool/.pixi/envs
       Manifest dir: /home/tpool/.pixi/manifests/pixi-global.toml

Workspace
------------
               Name: robojo
            Version: 0.1.0
      Manifest file: /home/tpool/robojo/pixi.toml
       Last updated: 17-09-2025 11:03:44

Environments
------------
        Environment: default
           Features: default
           Channels: https://conda.modular.com/max-nightly, conda-forge
   Dependency count: 1
       Dependencies: mojo
   Target platforms: linux-64
    Prefix location: /home/tpool/robojo/.pixi/envs/default
```

Running `mojo` gives
`mojo-lldb: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory`

**Comment by Ahajha** [comment]
Thanks, I've reopened for now.

**Comment by ThomasMader** [comment]
The mojo-lldb binary needs the shared libbsd library and on NixOS this does not work out of the box.
To fix it you should statically compile it.

@taylorpool you should be able to get it to work if you add the following to your NixOS configuration.

```
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      # libraries needed for modular/mojo
      libbsd
    ];
  };
```

**Comment by ThomasMader** [comment]
It should also be possible to fix it by providing libbsd via pixi I guess because some other dynamic libraries are provided like that.

```
$ ldd mojo-lldb
        linux-vdso.so.1 (0x00007ff09ac76000)
        libm.so.6 => /nix/store/g8zyryr9cr6540xsyg4avqkwgxpnwj2a-glibc-2.40-66/lib/libm.so.6 (0x00007ff09ab27000)
        libstdc++.so.6 => /home/thomad/dev/tmp/quickstart/.pixi/envs/default/bin/./../lib/libstdc++.so.6 (0x00007ff09a93a000)
        liblldb22.0.0git.so => /home/thomad/dev/tmp/quickstart/.pixi/envs/default/bin/./../lib/liblldb22.0.0git.so (0x00007ff092a00000)
        libgcc_s.so.1 => /home/thomad/dev/tmp/quickstart/.pixi/envs/default/bin/./../lib/libgcc_s.so.1 (0x00007ff09a91b000)
        libc.so.6 => /nix/store/g8zyryr9cr6540xsyg4avqkwgxpnwj2a-glibc-2.40-66/lib/libc.so.6 (0x00007ff092600000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/g8zyryr9cr6540xsyg4avqkwgxpnwj2a-glibc-2.40-66/lib64/ld-linux-x86-64.so.2 (0x00007ff09ac78000)
        libdl.so.2 => /nix/store/g8zyryr9cr6540xsyg4avqkwgxpnwj2a-glibc-2.40-66/lib/libdl.so.2 (0x00007ff09a914000)
        libncurses.so.6 => /home/thomad/dev/tmp/quickstart/.pixi/envs/default/bin/./../lib/libncurses.so.6 (0x00007ff09a8ea000)
        libtinfo.so.6 => /home/thomad/dev/tmp/quickstart/.pixi/envs/default/bin/./../lib/libtinfo.so.6 (0x00007ff0929bd000)
        libpanel.so.6 => /home/thomad/dev/tmp/quickstart/.pixi/envs/default/bin/./../lib/libpanel.so.6 (0x00007ff09a8e3000)
        libbsd.so.0 => not found
```
