### ISSUE TITLE
[BUG] the VScode language support seems to have a problem

### ISSUE THREAD

**Issue by duartemolha** [modular/modular#4418]
### Actual behavior

a variable that is initiated and then used in a function but if you hover over it you see the mojo error by the mojo language extention in vscode

unused variable 'start'mojo

### Expected behavior

the start variable here is clearly used on the next method should not highlight this problem.

### Steps to reproduce

here is the code on game of life

```
def main():
    start = Grid.random(128, 128)
    run_display(start)
```
in VScode if you hover over the start variable you get a error :

**_unused variable 'start'mojo_**

### System information

magic info
     Magic version: 0.7.2
System
------------
       Pixi version: 0.41.4
           Platform: linux-64
   Virtual packages: __unix=0=0
                   : __linux=5.15.167.4=0
                   : __glibc=2.39=0
                   : __archspec=1=skylake
          Cache dir: /home/duartem/.cache/rattler/cache
       Auth storage: /home/duartem/.rattler/credentials.json
   Config locations: No config files found

Global
------------
            Bin dir: /home/duartem/.modular/bin
    Environment dir: /home/duartem/.modular/envs
       Manifest dir: /home/duartem/.modular/manifests/pixi-global.toml

Project
------------
               Name: test_mojo
            Version: 0.1.0
      Manifest file: /home/duartem/src/test_mojo/mojoproject.toml
       Last updated: 23-04-2025 00:45:44

Environments
------------
        Environment: default
           Features: default
           Channels: https://conda.modular.com/max-nightly, https://conda.modular.com/max, https://repo.prefix.dev/modular-community, conda-forge
   Dependency count: 3
       Dependencies: max, python, pygame
   Target platforms: linux-64
-

**Comment by hstm** [comment]
Same problem here. The cause seems to be a mismatch between my project's Mojo SDK version (25.3.x) and the one installed by the VS Code plugin (25.2.0).

You can fix this by selecting the correct SDK in VS Code.

In VS Code, go to Extensions -> Mojo -> Settings -> Mojo.SDK: Additional SDKs.

Enter the path to your Mojo SDK here. If you followed the Game of Life tutorial, the path should be something like

`<path_to_your_project_dir>/life/.magic/envs/default/share/max`

(Please modify the path according to your setup. You should find a modular.cfg in the max directory.)

After adding the additional SDK, switch back to your Mojo code, and select the new SDK by clicking on "MAX SDK: <path>" in the bottom bar of VS Code to select your new SDK.

<img width="668" alt="Image" src="https://github.com/user-attachments/assets/02d585bd-0823-497d-853e-ea690b733c2a" />

After restarting VS Code, your falsely flagged "unused variable" errors etc. should be gone.

Hope this helps.

**Comment by duartemolha** [comment]
I do not have this in VSCODE
 Mojo -> Settings -> Mojo.SDK: Additional SDKs.

**Comment by hstm** [comment]
> I do not have this in VSCODE Mojo -> Settings -> Mojo.SDK: Additional SDKs.

So you're not using the Mojo extension in VS Code or don't you find the extension settings?

If you have installed the Mojo extension, this is how you can access the extension settings:

- in VS Code, choose "Extensions" on the left
- find the Mojo extension in the list of installed extensions
- in the Mojo extension, you will find a litte gear icon in the lower right. Click on the gear and select "Settings" from the menu

You then should see something similar to this:

<img width="1663" alt="Image" src="https://github.com/user-attachments/assets/3b4c85a7-bfce-4857-a662-3f214349232f" />

**Comment by duartemolha** [comment]
that entire Mojo.SDK is not shown on my vscode

**Comment by AmaranthineCodices** [comment]
Hi! This issue should be fixed in our current nightly builds, and will ship to the stable branch in 25.3. You can use the nightly Mojo extension to try it out now.

**Comment by Jerry050512** [comment]
Add an extra breakline at the first line of a function can dismiss the warning. Like this:
```mojo
def main():
    
    start = Grid.random(128, 128)
    run_display(start)
```
This is my temporarily solution😂 (Note that the first line has 4 spaces, or you'd better add a comment)

**Comment by soraros** [comment]
@AmaranthineCodices I don't think this issue is entirely fixed. The tooltip is still wrong for the first variable in a raising function.

<img width="191" alt="Image" src="https://github.com/user-attachments/assets/8bb80950-edff-4457-b728-6ed223d7e816" />

**Comment by AmaranthineCodices** [comment]
That's a separate issue that's unrelated to the problem described in the original issue.

**Comment by godardt** [comment]
> I do not have this in VSCODE Mojo -> Settings -> Mojo.SDK: Additional SDKs.

I'm running into the same issue in both the Mojo extension and Mojo extension nightly:

<img width="1139" alt="Image" src="https://github.com/user-attachments/assets/46ea9e12-4f05-41a5-a995-d4422135be4d" />

As a result, I'm unable to use VSCode with the `magic` environment and I have to rely on the command line everytime.

**Comment by godardt** [comment]
Okay, so the option is present if I use VSCode locally on my MacBook Air M2, but it is absent if I connect VSCode remotely to my Ubuntu 24.04 machine.

**Comment by godardt** [comment]
@hstm How did you manage to run your Mojo files in the `magic` environment? With the explanations you provided it only barely works.
VSCode seems to find the MAX package and run in the environment but any Python package I install in that same environment seems to be ignored. Looking at the command that it runs, it uses `mojo <myfile>.mojo` instead of `magic run <myfile>.mojo`.

For example, running the `life.mojo` example from the "Getting started" guide with the following env `/Users/Myself/workspace/mojo_test/life/.magic/envs/default/share/max` as the SDK path gives:
```
❯ /Users/Myself/workspace/mojo_test/life/.magic/envs/default/bin/mojo run /Users/Myself/workspace/mojo_test/life/life.mojo
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: while locating crashpad handler: unable to locate crashpad handler executable
Unhandled exception caught during execution: No module named 'pygame'
/Users/Myself/workspace/mojo_test/life/.magic/envs/default/bin/mojo: error: execution exited with a non-zero result: 1
```
However, running from the shell:
```
❯ magic run mojo life.mojo
pygame 2.6.1 (SDL 2.32.54, Python 3.13.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
```
Works perfectly.

Seems like I need a way to override VSCode default `mojo <file>` with `magic run mojo <file>`.

**Comment by conorbronsdon** [comment]
Status update: The original reported issue (false diagnostics from SDK version mismatch) should be fixed as of [v0.25.3](https://docs.modular.com/mojo/changelog/)+. However, this thread has picked up a few related-but-distinct problems around SDK path settings on remote [VS Code](https://marketplace.visualstudio.com/items?itemName=modular-mojotools.vscode-mojo) and `magic run` integration.

If the original false diagnostic issue is still happening for anyone on 25.3+, please comment here. The remote VS Code and `magic run` concerns might be better tracked as separate issues so they don't get lost in this thread.
