### ISSUE TITLE
[BUG] Incorrect exclusivity error when printing a StringSlice

### ISSUE THREAD

**Issue by soraros** [modular/modular#4790]
### Bug description

This should work but fails with exclusivity error:

```
fn main():
  print(String("test").removeprefix("")) 
```

**Comment by martinvuyk** [comment]
AFAIK `StringSlice` cannot be implicitly converted to `String` to avoid invisible allocations

**Comment by soraros** [comment]
That makes sense. Maybe the conversion should go the other way around. In any case, this was caught in #4789.

**Comment by martinvuyk** [comment]
Ok but that is correct behavior. There should be an overload for `StringSlice` and no implicit allocations should take place

**Comment by soraros** [comment]
This also doesn't work:
```mojo
fn main():
  print(String("test").removeprefix(""))  # error: argument of '__init__' call allows writing a memory location previously readable through another aliased argument
```

**Comment by soraros** [comment]
Actually, it's more of a problem with `StringSlice` not being `Eq`, since we do have a `EqualityComparable & Stringable` overload for `debug_assert`.

**Comment by martinvuyk** [comment]
> This also doesn't work:
> 
> fn main():
>   print(String("test").removeprefix(""))  # error: argument of '__init__' call allows writing a memory location previously readable through another aliased argument

Yeah I hate that error, have gotten it in a lot of places where it makes no sense. It's more of an error for anonymous origins (you even opened #4742 )

**Comment by lattner** [comment]
I agree the first issue isn't an issue.  I agree the print origin thing is really bad, it looks related to variadic pack handling.

**Comment by lattner** [comment]
Incidentally, while VariadicPack can/should be fixed, there is a deeper problem here.  The issue is that StringSlice allows itself to be unconditionally "writable" with a parametric mutability.  You can try make it force an immutable origin for writability - this would cause an implicit conversion from mutable slice to immutable slice, which will probably make lots of things better.

**Comment by martinvuyk** [comment]
@lattner there is still an issue with the origin, even when using `.get_immutable()`. I opened #4846 to track it
