### ISSUE TITLE
[BUG] SIMD.shuffle(IndexList) does not behave as documented

### ISSUE THREAD

**Issue by HJLebbink** [modular/modular#5297]
### Actual behavior
When you run the following code:
```
from utils import IndexList

fn main():
    var data = SIMD[DType.float32, 8](1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0)
    alias perm = IndexList[8](0,1,2,3,4,5,6,7)
    var data_out: SIMD[DType.float32, 8] = data.shuffle[perm]()
    print("data_out=" + String(data_out))
```
### Expected behavior
I expect this code to compile, as documented here https://docs.modular.com/mojo/stdlib/builtin/simd/SIMD#shuffle

### Observed behavior
```
error: no matching method in call to 'shuffle'
    var data_out: SIMD[DType.float32, 8] = data.shuffle[perm]()
                                           ~~~~~~~~~~~~~~~~~~^~
/mnt/c/Source/Github/sort-networks-mojo/question.mojo:1:1: note: candidate not viable: callee parameter #2 has 'Int' type, but value has type 'IndexList[8]'
from utils import IndexList
^
/mnt/c/Source/Github/sort-networks-mojo/question.mojo:1:1: note: candidate not viable: missing 1 required positional argument: 'other'
from utils import IndexList
^
/mnt/c/Source/Github/sort-networks-mojo/question.mojo:1:1: note: candidate not viable: callee parameter #2 has 'DType' type, but value has type 'IndexList[8]'
from utils import IndexList
^
/mnt/c/Source/Github/sort-networks-mojo/question.mojo:1:1: note: candidate not viable: missing 1 required positional argument: 'other'
from utils import IndexList
^
mojo: error: failed to parse the provided Mojo source module
```

Either the documentation is not correctly describing what to expect from this function, or the function is just malfunctioning. Also note that the error messages are not useful. 

Mojo 0.25.6.0.dev2025090805 (1f84bce6)

Either way, if someone knows how to use this function. Please let me know.

### System information

- Provide the system information by running `pixi info`.

System
------------
       Pixi version: 0.54.2
           Platform: linux-64
   Virtual packages: __unix=0=0
                   : __linux=6.6.87.2=0
                   : __glibc=2.39=0
                   : __cuda=12.8=0
                   : __archspec=1=sapphirerapids
          Cache dir: /home/henk/.cache/rattler/cache
       Auth storage: /home/henk/.rattler/credentials.json
   Config locations: /home/henk/.pixi/config.toml

Global
------------
            Bin dir: /home/henk/.pixi/bin
    Environment dir: /home/henk/.pixi/envs
       Manifest dir: /home/henk/.pixi/manifests/pixi-global.toml

Workspace
------------
               Name: sort-networks-mojo
            Version: 0.1.0
      Manifest file: /home/pixi.toml
       Last updated: 09-09-2025 19:14:15

Environments
------------
        Environment: default
           Features: default
           Channels: https://conda.modular.com/max-nightly, conda-forge
   Dependency count: 1
       Dependencies: modular
   Target platforms: linux-64
    Prefix location: /home/.pixi/envs/default

**Comment by soraros** [comment]
Syntax error. You should have used `()` instead.

**Comment by HJLebbink** [comment]
@soraros Thanx for the quick reply, 

The braces in the initialiser were just something I tried and shouldn’t have been in the repro code.

Still, whether I use
```go
var data_out: SIMD[DType.float32, 8] = data.shuffle[perm]()
```
or
```go
var data_out: SIMD[DType.float32, 8] = data.shuffle(perm)
````
I can’t get this example to compile.

**Comment by soraros** [comment]
Looks like another duplicate of #4199.

This works though.
```mojo
from utils import IndexList

fn main():
  var data = SIMD[DType.float32, 8](1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0)
  alias perm = IndexList[8](0, 1, 2, 3, 4, 5, 6, 7)
  var data_out = data.shuffle[mask=perm]()
  print(data_out)
```

**Comment by HJLebbink** [comment]
Shuffle used to work a year ago, a bit worrying that there isn’t a test covering this function...

The `shuffle[*mask: Int](self) -> Self` works. So if anyone (@soraros) know a way to do:

`fn index_list_to_variadic_list[size: Int](list: IndexList[size]) -> VariadicList[Int]:`

I at least can continue.

**Comment by JoeLoser** [comment]
> Shuffle used to work a year ago, a bit worrying that there isn’t a test covering this function...
> 
> The `shuffle[*mask: Int](self) -> Self` works. So if anyone ([@soraros](https://github.com/soraros)) know a way to do:
> 
> `fn index_list_to_variadic_list[size: Int](list: IndexList[size]) -> VariadicList[Int]:`
> 
> I at least can continue.

Here is the unit tests for `shuffle`: https://github.com/modular/modular/blob/e3fc382cd80729bc0ffe641a67bdd125d1ffce8e/mojo/stdlib/test/builtin/test_simd.mojo#L994 (this function and below neighboring ones).  If there's something specific missing here, feel free to open a PR.

**Comment by soraros** [comment]
@JoeLoser I think we could improve the test coverage here a little bit, I will make a PR soon.

**Comment by HJLebbink** [comment]
Did someone fix this yesterday? in Mojo 0.25.6.0.dev2025091000 (7f575ef6) this issue is fixed.

**Comment by soraros** [comment]
@HJLebbink I don't think so. Your repro still fails on `Mojo 0.25.6.0.dev2025091406 (99200739)`.

**Comment by soraros** [comment]
I think this is fixed in `Mojo 0.26.2.0.dev2026022005 (e5c435ed)` (ref: https://github.com/modular/modular/issues/4199#issuecomment-3923934954).
